### Author Login
POST http://localhost:6000/auth/login
Content-Type: application/json

{
    "email": "author1@gmail.com",
    "password": "author1"
}

### Logout
GET  http://localhost:6000/auth/logout

### Change Password
PUT http://localhost:6000/auth/change-password
Content-Type: application/json

{
    "currentPassword": "author123",
    "newPassword": "author1"
}

### Register Author
POST http://localhost:6000/auth/register
Content-Type: application/json

{
    "firstName": "author",
    "lastName":"2",
    "email": "author2@gmail.com",
    "role": "author", 
    "password": "author2",
    "profileImageUrl": "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
}

### Create Article
POST http://localhost:6000/author-api/articles
Content-Type: application/json

{
    "author": "69f65b0af677fd4acaf5d98c",
    "title": "My first Article",
    "content": "This is the content of my first article.",
    "category": "Introduction"
}


### Read Own Article
GET http://localhost:6000/author-api/articles


### Update Article
PUT http://localhost:6000/author-api/articles
Content-Type: application/json

{
    "articleId": "69f65b43f677fd4acaf5d995",
    "title": "My Updated Article",
    "content": "This is the updated content of my article.",
    "category": "Updated Category"
}


### Soft Delete Article by Article ID
PATCH http://localhost:6000/author-api/articles
Content-Type: application/json

{
    "articleId": "69f65b43f677fd4acaf5d995",
    "isArticleActive": true

}