### Admin Login
POST http://localhost:6000/auth/login
Content-Type: application/json

{
    "email": "admin01@gmail.com",
    "password": "admin1"
}

### Logout
GET  http://localhost:6000/auth/logout

### Change Password
PUT http://localhost:6000/auth/change-password
Content-Type: application/json

{
    "currentPassword": "admin01",
    "newPassword": "admin1"
}


### Read All Users and Authors (email & id)


### Block User or Author by ID
PATCH http://localhost:6000/admin-api/activity
Content-Type: application/json

{
    "email": "",
    "isActive": false
}